mod_id=ravens_mod_template
mod_name=Raven's Mod Template
mod_version=1.0.0
mod_group=io.github.recrivenvi.modtemplate
mod_side=both
mod_authors=RavenYin
mod_license=MIT
mod_description=由 RavenYin 制作的多版本模组模板

org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.workers.max=2
